# Generated by Django 3.1.2 on 2020-11-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='utl',
            new_name='url',
        ),
    ]
